[build]
  command = "npm install && npm run next:build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Serve static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Next.js App Router - all routes go to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
